#!/bin/sh

. $(dirname "$0")/../init.sh

clear
DOCKER_DIR
cd devbox/mini
OCAK "MINI DEVBOX (PHP ONLY)" "$_OCAK_INTRO" "$_OCAK_OWN" "" "START CONTAINER:" ">> $APP_NAME"
BR
docker-compose up -d
SLEEP1
OCAK "COMMAND STOP CONTAINER:" "bash deploy/halt"
