version: '3'
services:
    devbox:
        container_name: devbox
        build: ./devbox
        image: devbox/app:0.0.1
        ports:
            - "80:80"
        volumes:
            - ../../pj-app:/var/www/pj-app
    devbox_mysql:
        container_name: devboxdb
        image: mariadb
        ports:
            - "3306:3306"
        volumes:
            - ./data/mysql:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: root
        external_links:
            - devboxdb
