version: '3'
services:
    devbox_php_nginx:
        container_name: devbox_php_nginx
        build: .
        ports:
            - "7000:7000" # http://devbox.local:7000
        volumes:
            - ./../..:/var/www
            - ./nginx/00-devbox.conf:/etc/nginx/conf.d/00-devbox.conf
            - ./nginx/configs:/etc/nginx/sites-enabled
            - ./nginx/conf-stacks:/etc/nginx/conf-stacks
            - ./php/00-php.ini:/etc/php/7.2/fpm/conf.d/00-php.ini
        # links:
        #     - memcached
        #     - db

    # db:
    #     container_name: db
    #     image: mariadb
    #     restart: always
    #     ports:
    #         - "7100:3306"
    #     volumes:
    #         - ./data/mysql:/var/lib/mysql
    #     environment:
    #         MYSQL_ROOT_PASSWORD: root
    #
    # memcached:
    #     container_name: memcached
    #     image: memcached
    #     restart: always
    #     ports:
    #         - "11711:11211"
