#!/bin/sh

. $(dirname "$0")/init.sh

clear
DOCKER_DIR
OCAK "$_OCAK_INTRO" "$_OCAK_OWN" "" "START CONTAINER:" ">> $APP_NAME" ">> $DB_NAME"
BR
OCAK "COMMAND STOP CONTAINER:" "command + c / ctrl + c"
BR
OCAK "STARTING NOW:"
SLEEP2
docker-compose build --no-cache
